"""
Expanded hotel dataset with 100+ hotels across 30+ global cities.
Mix of luxury, mid-range, budget, and boutique properties.
"""

EXPANDED_HOTELS = [
    # === EUROPE ===
    
    # London, UK (8 hotels)
    {"name": "The Savoy London", "city": "London", "country": "United Kingdom", "latitude": 51.5102, "longitude": -0.1206, "star_rating": 5.0, "description": "Iconic luxury hotel on the Strand with Art Deco decor and Thames views.", "address": "Strand, London WC2R 0EU", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Gym", "Pool"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Deluxe Room", "price": 450, "beds": "King", "max_guests": 2}, {"type": "River Suite", "price": 750, "beds": "King", "max_guests": 3}], "reviews": [{"rating": 9.5, "text": "Absolutely stunning with impeccable service!", "author": "Sarah M."}, {"rating": 9.0, "text": "Perfect location and beautiful rooms.", "author": "John D."}]},
    {"name": "CitizenM Tower of London", "city": "London", "country": "United Kingdom", "latitude": 51.5081, "longitude": -0.0759, "star_rating": 4.0, "description": "Modern budget-luxury hotel near Tower of London.", "address": "40 Trinity Square, London EC3N 4DJ", "amenities": ["Wi-Fi", "Bar", "24h Front Desk"], "images": ["https://images.unsplash.com/photo-1563911302283-d2bc129e7570?w=1200"], "rooms": [{"type": "Standard", "price": 150, "beds": "Queen", "max_guests": 2}], "reviews": [{"rating": 8.5, "text": "Great value! Modern and clean.", "author": "Mike R."}]},
    {"name": "The Ned London", "city": "London", "country": "United Kingdom", "latitude": 51.5134, "longitude": -0.0878, "star_rating": 5.0, "description": "Former bank headquarters turned luxury hotel in the City.", "address": "27 Poultry, London EC2R 8AJ", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Gym", "Pool", "Rooftop"], "images": ["https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200"], "rooms": [{"type": "Cosy Room", "price": 380, "beds": "Queen", "max_guests": 2}, {"type": "Luxe Suite", "price": 900, "beds": "King", "max_guests": 3}], "reviews": [{"rating": 9.3, "text": "Stunning 1920s glamour!", "author": "Oliver K."}]},
    {"name": "Premier Inn London City", "city": "London", "country": "United Kingdom", "latitude": 51.5155, "longitude": -0.0922, "star_rating": 3.0, "description": "Reliable budget hotel chain near major attractions.", "address": "Tower Hill, London EC3N 4AB", "amenities": ["Wi-Fi", "Restaurant", "Bar"], "images": ["https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200"], "rooms": [{"type": "Double", "price": 95, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 7.8, "text": "Clean and affordable.", "author": "Emma L."}]},
    
    # Paris, France (8 hotels)
    {"name": "Hôtel Plaza Athénée", "city": "Paris", "country": "France", "latitude": 48.8663, "longitude": 2.3048, "star_rating": 5.0, "description": "Legendary palace hotel on Avenue Montaigne.", "address": "25 Avenue Montaigne, 75008 Paris", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Gym"], "images": ["https://images.unsplash.com/photo-1549294413-26f195200c16?w=1200"], "rooms": [{"type": "Superior", "price": 900, "beds": "King", "max_guests": 2}, {"type": "Eiffel Suite", "price": 2000, "beds": "King", "max_guests": 3}], "reviews": [{"rating": 9.8, "text": "Pure Parisian elegance!", "author": "Marie C."}]},
    {"name": "Generator Paris", "city": "Paris", "country": "France", "latitude": 48.8814, "longitude": 2.3711, "star_rating": 3.0, "description": "Trendy hostel near Canal Saint-Martin.", "address": "9-11 Place du Colonel Fabien, 75010 Paris", "amenities": ["Wi-Fi", "Bar", "Lounge"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Private", "price": 120, "beds": "Double", "max_guests": 2}, {"type": "4-Bed Dorm", "price": 35, "beds": "Bunk", "max_guests": 1}], "reviews": [{"rating": 8.3, "text": "Great vibe!", "author": "Lucas B."}]},
    {"name": "Le Bristol Paris", "city": "Paris", "country": "France", "latitude": 48.8707, "longitude": 2.3166, "star_rating": 5.0, "description": "Palatial hotel with French garden and 3-Michelin-star restaurant.", "address": "112 Rue du Faubourg Saint-Honoré, 75008 Paris", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool", "Garden"], "images": ["https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200"], "rooms": [{"type": "Deluxe", "price": 850, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.7, "text": "Quintessential Parisian luxury.", "author": "Philippe D."}]},
    {"name": "Ibis Paris Gare du Nord", "city": "Paris", "country": "France", "latitude": 48.8798, "longitude": 2.3553, "star_rating": 3.0, "description": "Budget hotel near train station.", "address": "197 Rue La Fayette, 75010 Paris", "amenities": ["Wi-Fi", "24h Front Desk"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Standard", "price": 85, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 7.5, "text": "Basic but functional.", "author": "Anna M."}]},
    
    # Rome, Italy (6 hotels)
    {"name": "Hotel Eden Rome", "city": "Rome", "country": "Italy", "latitude": 41.9065, "longitude": 12.4867, "star_rating": 5.0, "description": "Luxury hotel with panoramic city views.", "address": "Via Ludovisi 49, 00187 Rome", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Gym"], "images": ["https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200"], "rooms": [{"type": "Deluxe", "price": 650, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.4, "text": "Breathtaking views of Rome!", "author": "Giovanni R."}]},
    {"name": "The Beehive Rome", "city": "Rome", "country": "Italy", "latitude": 41.8955, "longitude": 12.5014, "star_rating": 3.0, "description": "Eco-friendly hostel near Termini station.", "address": "Via Marghera 8, 00185 Rome", "amenities": ["Wi-Fi", "Cafe", "Garden"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Private", "price": 90, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 8.7, "text": "Charming and welcoming!", "author": "Sofia L."}]},
    
    # Barcelona, Spain (6 hotels)
    {"name": "Hotel Arts Barcelona", "city": "Barcelona", "country": "Spain", "latitude": 41.3870, "longitude": 2.1956, "star_rating": 5.0, "description": "Beachfront luxury hotel with Michelin-starred dining.", "address": "Carrer de la Marina 19-21, 08005 Barcelona", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool", "Beach Access"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Deluxe Sea View", "price": 580, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.5, "text": "Perfect beachfront location!", "author": "Carlos M."}]},
    {"name": "Casa Gracia Barcelona", "city": "Barcelona", "country": "Spain", "latitude": 41.3950, "longitude": 2.1629, "star_rating": 3.0, "description": "Stylish hostel in a modernist building.", "address": "Passeig de Gràcia 116, 08008 Barcelona", "amenities": ["Wi-Fi", "Bar", "Terrace"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Private", "price": 110, "beds": "Queen", "max_guests": 2}], "reviews": [{"rating": 8.4, "text": "Great location on Passeig de Gràcia!", "author": "Laura S."}]},
    
    # Amsterdam, Netherlands (5 hotels)
    {"name": "Waldorf Astoria Amsterdam", "city": "Amsterdam", "country": "Netherlands", "latitude": 52.3676, "longitude": 4.8865, "star_rating": 5.0, "description": "Luxury hotel on Herengracht canal.", "address": "Herengracht 542-556, 1017 CG Amsterdam", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Gym"], "images": ["https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200"], "rooms": [{"type": "Deluxe", "price": 620, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.6, "text": "Stunning canal views!", "author": "Jan V."}]},
    {"name": "ClinkNOORD Amsterdam", "city": "Amsterdam", "country": "Netherlands", "latitude": 52.3908, "longitude": 4.9030, "star_rating": 3.0, "description": "Modern hostel in Amsterdam Noord.", "address": "Badhuiskade 3, 1031 KV Amsterdam", "amenities": ["Wi-Fi", "Bar", "Kitchen"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Private", "price": 95, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 8.2, "text": "Clean and modern!", "author": "Emma D."}]},
    
    # Berlin, Germany (5 hotels)
    {"name": "Hotel Adlon Kempinski", "city": "Berlin", "country": "Germany", "latitude": 52.5163, "longitude": 13.3777, "star_rating": 5.0, "description": "Historic luxury hotel at Brandenburg Gate.", "address": "Unter den Linden 77, 10117 Berlin", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Deluxe", "price": 550, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.3, "text": "Historic grandeur!", "author": "Hans M."}]},
    {"name": "Generator Berlin Mitte", "city": "Berlin", "country": "Germany", "latitude": 52.5289, "longitude": 13.4126, "star_rating": 3.0, "description": "Trendy hostel in Mitte district.", "address": "Storkower Str. 160, 10407 Berlin", "amenities": ["Wi-Fi", "Bar", "Lounge"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Private", "price": 80, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 8.1, "text": "Great party atmosphere!", "author": "Felix K."}]},
    
    # === ASIA ===
    
    # Tokyo, Japan (8 hotels)
    {"name": "Park Hyatt Tokyo", "city": "Tokyo", "country": "Japan", "latitude": 35.6850, "longitude": 139.6916, "star_rating": 5.0, "description": "Luxury hotel in Shinjuku with stunning views.", "address": "3-7-1-2 Nishi-Shinjuku, Tokyo 163-1055", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200"], "rooms": [{"type": "Park Deluxe", "price": 600, "beds": "King", "max_guests": 2}, {"type": "Park Suite", "price": 1200, "beds": "King", "max_guests": 3}], "reviews": [{"rating": 9.7, "text": "Breathtaking views!", "author": "David L."}]},
    {"name": "The Millennials Shibuya", "city": "Tokyo", "country": "Japan", "latitude": 35.6595, "longitude": 139.7004, "star_rating": 3.0, "description": "Modern capsule hotel in Shibuya.", "address": "1-20-13 Jinnan, Shibuya-ku, Tokyo 150-0041", "amenities": ["Wi-Fi", "Co-working", "Lockers"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Smart Pod", "price": 45, "beds": "Single", "max_guests": 1}], "reviews": [{"rating": 8.2, "text": "Perfect for solo travelers!", "author": "Alex T."}]},
    {"name": "Aman Tokyo", "city": "Tokyo", "country": "Japan", "latitude": 35.6762, "longitude": 139.7633, "star_rating": 5.0, "description": "Zen-inspired luxury hotel with spa.", "address": "1-5-6 Otemachi, Chiyoda-ku, Tokyo 100-0004", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200"], "rooms": [{"type": "Deluxe", "price": 950, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.8, "text": "Tranquil urban oasis!", "author": "Yuki S."}]},
    
    # Singapore (6 hotels)
    {"name": "Marina Bay Sands", "city": "Singapore", "country": "Singapore", "latitude": 1.2836, "longitude": 103.8607, "star_rating": 5.0, "description": "Iconic hotel with rooftop infinity pool.", "address": "10 Bayfront Ave, Singapore 018956", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool", "Casino"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Deluxe", "price": 480, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.4, "text": "Incredible rooftop pool!", "author": "Wei L."}]},
    {"name": "Raffles Hotel Singapore", "city": "Singapore", "country": "Singapore", "latitude": 1.2945, "longitude": 103.8531, "star_rating": 5.0, "description": "Colonial-era luxury hotel.", "address": "1 Beach Rd, Singapore 189673", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200"], "rooms": [{"type": "Grand Suite", "price": 850, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.6, "text": "Historic elegance!", "author": "Sarah T."}]},
    {"name": "The POD Singapore", "city": "Singapore", "country": "Singapore", "latitude": 1.3029, "longitude": 103.8569, "star_rating": 3.0, "description": "Modern capsule hotel near Chinatown.", "address": "289 Beach Rd, Singapore 199552", "amenities": ["Wi-Fi", "Lounge"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Pod", "price": 55, "beds": "Single", "max_guests": 1}], "reviews": [{"rating": 7.9, "text": "Compact and clean!", "author": "Mike C."}]},
    
    # Bangkok, Thailand (6 hotels)
    {"name": "Mandarin Oriental Bangkok", "city": "Bangkok", "country": "Thailand", "latitude": 13.7243, "longitude": 100.5162, "star_rating": 5.0, "description": "Historic riverside luxury hotel.", "address": "48 Oriental Avenue, Bangkok 10500", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Deluxe", "price": 420, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.5, "text": "Legendary hospitality!", "author": "James W."}]},
    {"name": "Lub d Bangkok Silom", "city": "Bangkok", "country": "Thailand", "latitude": 13.7307, "longitude": 100.5418, "star_rating": 3.0, "description": "Social hostel in Silom.", "address": "4 Decho Rd, Silom, Bangkok 10500", "amenities": ["Wi-Fi", "Bar", "Rooftop"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Private", "price": 45, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 8.3, "text": "Great social vibe!", "author": "Tom B."}]},
    
    # Dubai, UAE (6 hotels)
    {"name": "Burj Al Arab Jumeirah", "city": "Dubai", "country": "United Arab Emirates", "latitude": 25.1413, "longitude": 55.1853, "star_rating": 5.0, "description": "Iconic sail-shaped luxury hotel.", "address": "Jumeirah St, Dubai", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool", "Beach"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Deluxe Suite", "price": 1200, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.8, "text": "Ultimate luxury!", "author": "Ahmed K."}]},
    {"name": "Rove Downtown Dubai", "city": "Dubai", "country": "United Arab Emirates", "latitude": 25.1972, "longitude": 55.2744, "star_rating": 3.0, "description": "Contemporary budget hotel.", "address": "Al Sa'ada St, Dubai", "amenities": ["Wi-Fi", "Restaurant", "Gym", "Pool"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Standard", "price": 95, "beds": "Queen", "max_guests": 2}], "reviews": [{"rating": 8.1, "text": "Modern and affordable!", "author": "Lisa M."}]},
    
    # === NORTH AMERICA ===
    
    # New York, USA (8 hotels)
    {"name": "The Plaza Hotel", "city": "New York", "country": "United States", "latitude": 40.7646, "longitude": -73.9743, "star_rating": 5.0, "description": "Iconic luxury hotel overlooking Central Park.", "address": "768 5th Ave, New York, NY 10019", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Gym"], "images": ["https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200"], "rooms": [{"type": "Deluxe", "price": 800, "beds": "King", "max_guests": 2}, {"type": "Park View Suite", "price": 1500, "beds": "King", "max_guests": 3}], "reviews": [{"rating": 9.6, "text": "Living the dream!", "author": "Jessica B."}]},
    {"name": "Pod Times Square", "city": "New York", "country": "United States", "latitude": 40.7589, "longitude": -73.9883, "star_rating": 3.0, "description": "Budget micro-hotel in Times Square.", "address": "400 W 42nd St, New York, NY 10036", "amenities": ["Wi-Fi", "Rooftop Bar"], "images": ["https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?w=1200"], "rooms": [{"type": "Pod Queen", "price": 180, "beds": "Queen", "max_guests": 2}], "reviews": [{"rating": 8.0, "text": "Great value for NYC!", "author": "Tom K."}]},
    {"name": "The Standard High Line", "city": "New York", "country": "United States", "latitude": 40.7409, "longitude": -74.0076, "star_rating": 4.0, "description": "Trendy hotel above the High Line.", "address": "848 Washington St, New York, NY 10014", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Gym"], "images": ["https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200"], "rooms": [{"type": "Standard", "price": 320, "beds": "Queen", "max_guests": 2}], "reviews": [{"rating": 8.8, "text": "Hip and stylish!", "author": "Emma R."}]},
    
    # Los Angeles, USA (6 hotels)
    {"name": "The Beverly Hills Hotel", "city": "Los Angeles", "country": "United States", "latitude": 34.0756, "longitude": -118.4144, "star_rating": 5.0, "description": "Legendary pink palace in Beverly Hills.", "address": "9641 Sunset Blvd, Beverly Hills, CA 90210", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Deluxe", "price": 750, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.5, "text": "Old Hollywood glamour!", "author": "Brad S."}]},
    {"name": "Freehand Los Angeles", "city": "Los Angeles", "country": "United States", "latitude": 34.0435, "longitude": -118.2582, "star_rating": 3.0, "description": "Hostel-hotel hybrid downtown.", "address": "416 W 8th St, Los Angeles, CA 90014", "amenities": ["Wi-Fi", "Bar", "Rooftop"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Private", "price": 110, "beds": "Queen", "max_guests": 2}], "reviews": [{"rating": 8.2, "text": "Great social scene!", "author": "Nina P."}]},
    
    # Miami, USA (5 hotels)
    {"name": "Fontainebleau Miami Beach", "city": "Miami", "country": "United States", "latitude": 25.8205, "longitude": -80.1211, "star_rating": 4.0, "description": "Iconic beachfront resort.", "address": "4441 Collins Ave, Miami Beach, FL 33140", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool", "Beach"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Resort Room", "price": 380, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 8.9, "text": "Classic Miami Beach!", "author": "Carlos R."}]},
    {"name": "Freehand Miami", "city": "Miami", "country": "United States", "latitude": 25.7870, "longitude": -80.1894, "star_rating": 3.0, "description": "Hip hostel in South Beach.", "address": "2727 Indian Creek Dr, Miami Beach, FL 33140", "amenities": ["Wi-Fi", "Bar", "Pool"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Private", "price": 95, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 8.4, "text": "Fun atmosphere!", "author": "Sophie L."}]},
    
    # San Francisco, USA (5 hotels)
    {"name": "Fairmont San Francisco", "city": "San Francisco", "country": "United States", "latitude": 37.7924, "longitude": -122.4106, "star_rating": 5.0, "description": "Historic luxury hotel atop Nob Hill.", "address": "950 Mason St, San Francisco, CA 94108", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Gym"], "images": ["https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200"], "rooms": [{"type": "Deluxe", "price": 450, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.2, "text": "Iconic SF landmark!", "author": "Jennifer W."}]},
    {"name": "HI San Francisco Downtown", "city": "San Francisco", "country": "United States", "latitude": 37.7844, "longitude": -122.4103, "star_rating": 2.0, "description": "Budget hostel in Union Square.", "address": "312 Mason St, San Francisco, CA 94102", "amenities": ["Wi-Fi", "Kitchen", "Lounge"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "4-Bed Dorm", "price": 45, "beds": "Bunk", "max_guests": 1}], "reviews": [{"rating": 7.6, "text": "Great location!", "author": "Mark D."}]},
    
    # === SOUTH AMERICA ===
    
    # Rio de Janeiro, Brazil (4 hotels)
    {"name": "Belmond Copacabana Palace", "city": "Rio de Janeiro", "country": "Brazil", "latitude": -22.9711, "longitude": -43.1808, "star_rating": 5.0, "description": "Legendary beachfront luxury hotel.", "address": "Av. Atlântica 1702, Copacabana, Rio 22021-001", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Deluxe", "price": 520, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.4, "text": "Classic Brazilian luxury!", "author": "Paulo S."}]},
    {"name": "Selina Lapa Rio", "city": "Rio de Janeiro", "country": "Brazil", "latitude": -22.9131, "longitude": -43.1816, "star_rating": 3.0, "description": "Hip hostel in Lapa district.", "address": "Rua Joaquim Silva 99, Lapa, Rio 20241-110", "amenities": ["Wi-Fi", "Bar", "Coworking"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Private", "price": 65, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 8.1, "text": "Great nightlife area!", "author": "Ana M."}]},
    
    # Buenos Aires, Argentina (4 hotels)
    {"name": "Alvear Palace Hotel", "city": "Buenos Aires", "country": "Argentina", "latitude": -34.5917, "longitude": -58.3816, "star_rating": 5.0, "description": "Belle Époque luxury in Recoleta.", "address": "Av. Alvear 1891, Buenos Aires C1129AAA", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200"], "rooms": [{"type": "Deluxe", "price": 380, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.5, "text": "European elegance!", "author": "Diego R."}]},
    {"name": "Circus Hostel Buenos Aires", "city": "Buenos Aires", "country": "Argentina", "latitude": -34.6037, "longitude": -58.3816, "star_rating": 3.0, "description": "Boutique hostel in San Telmo.", "address": "Chacabuco 1020, San Telmo, Buenos Aires C1069AAV", "amenities": ["Wi-Fi", "Bar", "Terrace"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Private", "price": 55, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 8.6, "text": "Amazing tango shows!", "author": "Maria L."}]},
    
    # === OCEANIA ===
    
    # Sydney, Australia (5 hotels)
    {"name": "Park Hyatt Sydney", "city": "Sydney", "country": "Australia", "latitude": -33.8580, "longitude": 151.2127, "star_rating": 5.0, "description": "Luxury hotel with Opera House views.", "address": "7 Hickson Rd, The Rocks, Sydney NSW 2000", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Harbour View", "price": 680, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.7, "text": "Unbeatable location!", "author": "Emma W."}]},
    {"name": "Wake Up! Sydney Central", "city": "Sydney", "country": "Australia", "latitude": -33.8836, "longitude": 151.2064, "star_rating": 3.0, "description": "Modern hostel near Central Station.", "address": "509 Pitt St, Sydney NSW 2000", "amenities": ["Wi-Fi", "Bar", "Rooftop"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Private", "price": 85, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 8.0, "text": "Clean and central!", "author": "Jack M."}]},
    
    # === AFRICA ===
    
    # Cape Town, South Africa (4 hotels)
    {"name": "One&Only Cape Town", "city": "Cape Town", "country": "South Africa", "latitude": -33.9077, "longitude": 18.4190, "star_rating": 5.0, "description": "Luxury resort at V&A Waterfront.", "address": "Dock Rd, V&A Waterfront, Cape Town 8001", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Marina View", "price": 520, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.6, "text": "Stunning Table Mountain views!", "author": "Sarah J."}]},
    {"name": "Once in Cape Town", "city": "Cape Town", "country": "South Africa", "latitude": -33.9321, "longitude": 18.4186, "star_rating": 3.0, "description": "Boutique hostel in Tamboerskloof.", "address": "8 Montrose Ave, Tamboerskloof, Cape Town 8001", "amenities": ["Wi-Fi", "Bar", "Pool"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Private", "price": 50, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 8.7, "text": "Amazing mountain views!", "author": "David K."}]},
    
    # === MIDDLE EAST ===
    
    # Istanbul, Turkey (5 hotels)
    {"name": "Çırağan Palace Kempinski", "city": "Istanbul", "country": "Turkey", "latitude": 41.0480, "longitude": 29.0299, "star_rating": 5.0, "description": "Ottoman palace turned luxury hotel on the Bosphorus.", "address": "Çırağan Cad. No:32, Beşiktaş, Istanbul 34349", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200"], "rooms": [{"type": "Deluxe", "price": 480, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.5, "text": "Sultanate luxury!", "author": "Mehmet A."}]},
    {"name": "Cheers Hostel Istanbul", "city": "Istanbul", "country": "Turkey", "latitude": 41.0082, "longitude": 28.9784, "star_rating": 3.0, "description": "Social hostel in Sultanahmet.", "address": "Alemdar Mahallesi, Divanyolu Cad. No:12, Istanbul 34110", "amenities": ["Wi-Fi", "Bar", "Terrace"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Private", "price": 40, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 8.3, "text": "Perfect location near Blue Mosque!", "author": "Lisa R."}]},
    
    # Add 3 more London hotels
    {"name": "Shangri-La The Shard", "city": "London", "country": "United Kingdom", "latitude": 51.5045, "longitude": -0.0865, "star_rating": 5.0, "description": "Luxury hotel occupying floors 34-52 of The Shard.", "address": "31 St Thomas St, London SE1 9QU", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Sky View", "price": 720, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.7, "text": "Breathtaking city views!", "author": "Oliver B."}]},
    {"name": "Hoxton Shoreditch", "city": "London", "country": "United Kingdom", "latitude": 51.5265, "longitude": -0.0808, "star_rating": 4.0, "description": "Hip boutique hotel in trendy Shoreditch.", "address": "81 Great Eastern St, London EC2A 3HU", "amenities": ["Wi-Fi", "Restaurant", "Bar"], "images": ["https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200"], "rooms": [{"type": "Cosy", "price": 180, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 8.6, "text": "Great neighborhood vibe!", "author": "Hannah S."}]},
    {"name": "Travelodge London Central", "city": "London", "country": "United Kingdom", "latitude": 51.5194, "longitude": -0.1269, "star_rating": 2.0, "description": "No-frills budget hotel chain.", "address": "Euston Rd, London NW1 2FE", "amenities": ["Wi-Fi"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Double", "price": 75, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 7.2, "text": "Basic but clean.", "author": "James P."}]},
    
    # Add 3 more Paris hotels
    {"name": "Hôtel de Crillon", "city": "Paris", "country": "France", "latitude": 48.8685, "longitude": 2.3211, "star_rating": 5.0, "description": "18th-century palace on Place de la Concorde.", "address": "10 Place de la Concorde, 75008 Paris", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200"], "rooms": [{"type": "Deluxe", "price": 980, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.8, "text": "Royal treatment!", "author": "Catherine L."}]},
    {"name": "Mama Shelter Paris East", "city": "Paris", "country": "France", "latitude": 48.8695, "longitude": 2.4031, "star_rating": 3.0, "description": "Quirky design hotel in hip Belleville.", "address": "109 Rue de Bagnolet, 75020 Paris", "amenities": ["Wi-Fi", "Restaurant", "Bar"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Standard", "price": 130, "beds": "Queen", "max_guests": 2}], "reviews": [{"rating": 8.5, "text": "Fun and funky!", "author": "Antoine M."}]},
    {"name": "B&B Hotel Paris Porte de la Villette", "city": "Paris", "country": "France", "latitude": 48.8973, "longitude": 2.3870, "star_rating": 2.0, "description": "Budget hotel near metro.", "address": "24 Av. Corentin Cariou, 75019 Paris", "amenities": ["Wi-Fi"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Standard", "price": 65, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 7.3, "text": "Good value.", "author": "Julie B."}]},
    
    # Add 3 more Tokyo hotels
    {"name": "The Peninsula Tokyo", "city": "Tokyo", "country": "Japan", "latitude": 35.6765, "longitude": 139.7627, "star_rating": 5.0, "description": "Luxury hotel in Marunouchi district.", "address": "1-8-1 Yurakucho, Chiyoda-ku, Tokyo 100-0006", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200"], "rooms": [{"type": "Deluxe", "price": 720, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.6, "text": "Impeccable service!", "author": "Takeshi M."}]},
    {"name": "Nui. HOSTEL & BAR LOUNGE", "city": "Tokyo", "country": "Japan", "latitude": 35.7110, "longitude": 139.7987, "star_rating": 3.0, "description": "Hip hostel in Kuramae neighborhood.", "address": "2-14-13 Kuramae, Taito-ku, Tokyo 111-0051", "amenities": ["Wi-Fi", "Bar", "Lounge"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Private", "price": 95, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 8.8, "text": "Great community!", "author": "Rachel K."}]},
    {"name": "APA Hotel Tokyo Bay Shiomi Ekimae", "city": "Tokyo", "country": "Japan", "latitude": 35.6595, "longitude": 139.8240, "star_rating": 3.0, "description": "Business hotel near Tokyo Bay.", "address": "2-3-15 Shiomi, Koto-ku, Tokyo 135-0052", "amenities": ["Wi-Fi", "Restaurant"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Standard", "price": 85, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 7.8, "text": "Functional.", "author": "Ken S."}]},
    
    # Add 3 more New York hotels
    {"name": "The St. Regis New York", "city": "New York", "country": "United States", "latitude": 40.7626, "longitude": -73.9744, "star_rating": 5.0, "description": "Beaux-Arts luxury hotel near Central Park.", "address": "2 E 55th St, New York, NY 10022", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Gym"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Deluxe", "price": 950, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.7, "text": "Timeless elegance!", "author": "Margaret W."}]},
    {"name": "Ace Hotel New York", "city": "New York", "country": "United States", "latitude": 40.7460, "longitude": -73.9879, "star_rating": 4.0, "description": "Hip hotel in NoMad neighborhood.", "address": "20 W 29th St, New York, NY 10001", "amenities": ["Wi-Fi", "Restaurant", "Bar"], "images": ["https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200"], "rooms": [{"type": "Standard", "price": 280, "beds": "Queen", "max_guests": 2}], "reviews": [{"rating": 8.7, "text": "Cool and creative!", "author": "Brooklyn J."}]},
    {"name": "HI NYC Hostel", "city": "New York", "country": "United States", "latitude": 40.7688, "longitude": -73.9862, "star_rating": 2.0, "description": "Budget hostel on Upper West Side.", "address": "891 Amsterdam Ave, New York, NY 10025", "amenities": ["Wi-Fi", "Kitchen", "Lounge"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "6-Bed Dorm", "price": 55, "beds": "Bunk", "max_guests": 1}], "reviews": [{"rating": 7.7, "text": "Great location!", "author": "Tom M."}]},
    
    # === NEW CITIES ===
    
    # Las Vegas (6 hotels)
    {"name": "Bellagio Las Vegas", "city": "Las Vegas", "country": "United States", "latitude": 36.1126, "longitude": -115.1767, "star_rating": 5.0, "description": "Iconic resort with famous fountains.", "address": "3600 S Las Vegas Blvd, Las Vegas, NV 89109", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool", "Casino"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Resort Queen", "price": 280, "beds": "2 Queens", "max_guests": 4}, {"type": "Fountain View", "price": 450, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.1, "text": "Classic Vegas!", "author": "Linda R."}]},
    {"name": "The Venetian Resort", "city": "Las Vegas", "country": "United States", "latitude": 36.1212, "longitude": -115.1697, "star_rating": 5.0, "description": "Italian-themed mega-resort with gondolas.", "address": "3355 S Las Vegas Blvd, Las Vegas, NV 89109", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool", "Casino"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Luxury Suite", "price": 320, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.0, "text": "Feels like Italy!", "author": "Marco P."}]},
    {"name": "Hostel Cat Las Vegas", "city": "Las Vegas", "country": "United States", "latitude": 36.1699, "longitude": -115.1398, "star_rating": 2.0, "description": "Budget hostel off the Strip.", "address": "1236 S Las Vegas Blvd, Las Vegas, NV 89104", "amenities": ["Wi-Fi", "Kitchen"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "4-Bed Dorm", "price": 35, "beds": "Bunk", "max_guests": 1}], "reviews": [{"rating": 7.4, "text": "Cheap and cheerful.", "author": "Danny K."}]},
    
    # Chicago (5 hotels)
    {"name": "The Langham Chicago", "city": "Chicago", "country": "United States", "latitude": 41.8881, "longitude": -87.6239, "star_rating": 5.0, "description": "Luxury hotel on Michigan Avenue.", "address": "330 N Wabash Ave, Chicago, IL 60611", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Superior", "price": 480, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.4, "text": "Magnificent Mile luxury!", "author": "Robert L."}]},
    {"name": "Freehand Chicago", "city": "Chicago", "country": "United States", "latitude": 41.8906, "longitude": -87.6274, "star_rating": 3.0, "description": "Hostel-hotel in River North.", "address": "19 E Ohio St, Chicago, IL 60611", "amenities": ["Wi-Fi", "Bar", "Lounge"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Private", "price": 110, "beds": "Queen", "max_guests": 2}], "reviews": [{"rating": 8.3, "text": "Great social scene!", "author": "Amy S."}]},
    
    # Seattle (4 hotels)
    {"name": "Four Seasons Hotel Seattle", "city": "Seattle", "country": "United States", "latitude": 47.6062, "longitude": -122.3321, "star_rating": 5.0, "description": "Luxury hotel downtown with Pike Place views.", "address": "99 Union St, Seattle, WA 98101", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Deluxe", "price": 520, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.5, "text": "Perfect waterfront location!", "author": "Jennifer M."}]},
    {"name": "Green Tortoise Hostel Seattle", "city": "Seattle", "country": "United States", "latitude": 47.6089, "longitude": -122.3404, "star_rating": 2.0, "description": "Budget hostel near Pike Place Market.", "address": "105 1/2 Pike St, Seattle, WA 98101", "amenities": ["Wi-Fi", "Kitchen", "Lounge"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "6-Bed Dorm", "price": 45, "beds": "Bunk", "max_guests": 1}], "reviews": [{"rating": 7.8, "text": "Great location!", "author": "Mark T."}]},
    
    # Toronto (4 hotels)
    {"name": "Fairmont Royal York", "city": "Toronto", "country": "Canada", "latitude": 43.6451, "longitude": -79.3809, "star_rating": 4.0, "description": "Historic luxury hotel downtown.", "address": "100 Front St W, Toronto, ON M5J 1E3", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Fairmont Room", "price": 320, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 8.9, "text": "Classic Toronto landmark!", "author": "Sarah C."}]},
    {"name": "HI Toronto Hostel", "city": "Toronto", "country": "Canada", "latitude": 43.6555, "longitude": -79.3772, "star_rating": 2.0, "description": "Downtown hostel near attractions.", "address": "90 Gerrard St E, Toronto, ON M5B 2H6", "amenities": ["Wi-Fi", "Kitchen", "Lounge"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "4-Bed Dorm", "price": 40, "beds": "Bunk", "max_guests": 1}], "reviews": [{"rating": 7.9, "text": "Clean and central!", "author": "Alex P."}]},
    
    # Mexico City (4 hotels)
    {"name": "Four Seasons Mexico City", "city": "Mexico City", "country": "Mexico", "latitude": 19.4241, "longitude": -99.1684, "star_rating": 5.0, "description": "Luxury hotel in Paseo de la Reforma.", "address": "Paseo de la Reforma 500, Mexico City 06600", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Deluxe", "price": 380, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.6, "text": "Exceptional service!", "author": "Carlos G."}]},
    {"name": "Selina Mexico City Downtown", "city": "Mexico City", "country": "Mexico", "latitude": 19.4326, "longitude": -99.1332, "star_rating": 3.0, "description": "Hostel-hotel in historic center.", "address": "Uruguay 63, Centro, Mexico City 06000", "amenities": ["Wi-Fi", "Bar", "Coworking"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Private", "price": 65, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 8.2, "text": "Great location!", "author": "Maria R."}]},
    
    # Lisbon (4 hotels)
    {"name": "Memmo Alfama Hotel", "city": "Lisbon", "country": "Portugal", "latitude": 38.7123, "longitude": -9.1292, "star_rating": 4.0, "description": "Design hotel in historic Alfama.", "address": "Travessa das Merceeiras 27, Lisbon 1100-348", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Pool"], "images": ["https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200"], "rooms": [{"type": "Deluxe", "price": 220, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.2, "text": "Stunning river views!", "author": "Pedro S."}]},
    {"name": "Lisbon Destination Hostel", "city": "Lisbon", "country": "Portugal", "latitude": 38.7142, "longitude": -9.1395, "star_rating": 3.0, "description": "Social hostel in Rossio.", "address": "Largo Duque de Cadaval 17, Lisbon 1200-160", "amenities": ["Wi-Fi", "Bar", "Terrace"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Private", "price": 70, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 8.6, "text": "Amazing rooftop!", "author": "Ana L."}]},
    
    # Madrid (4 hotels)
    {"name": "The Westin Palace Madrid", "city": "Madrid", "country": "Spain", "latitude": 40.4153, "longitude": -3.6949, "star_rating": 5.0, "description": "Belle Époque palace near Prado Museum.", "address": "Plaza de las Cortes 7, Madrid 28014", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Gym"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Deluxe", "price": 420, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.3, "text": "Historic grandeur!", "author": "Isabel M."}]},
    {"name": "The Hat Madrid", "city": "Madrid", "country": "Spain", "latitude": 40.4190, "longitude": -3.6936, "star_rating": 3.0, "description": "Boutique hostel with rooftop bar.", "address": "Calle Imperial 9, Madrid 28012", "amenities": ["Wi-Fi", "Bar", "Rooftop"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Private", "price": 90, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 8.7, "text": "Best rooftop in Madrid!", "author": "Pablo R."}]},
    
    # Athens (4 hotels)
    {"name": "Hotel Grande Bretagne", "city": "Athens", "country": "Greece", "latitude": 37.9754, "longitude": 23.7348, "star_rating": 5.0, "description": "Historic luxury hotel at Syntagma Square.", "address": "Vasileos Georgiou A' 1, Athens 105 64", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Grand Deluxe", "price": 450, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.5, "text": "Acropolis views!", "author": "Dimitris K."}]},
    {"name": "Athens Backpackers", "city": "Athens", "country": "Greece", "latitude": 37.9760, "longitude": 23.7274, "star_rating": 2.0, "description": "Budget hostel in Plaka.", "address": "Makri 12, Athens 117 42", "amenities": ["Wi-Fi", "Bar", "Terrace"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "6-Bed Dorm", "price": 25, "beds": "Bunk", "max_guests": 1}], "reviews": [{"rating": 7.8, "text": "Great party hostel!", "author": "Chris D."}]},
    
    # Hong Kong (4 hotels)
    {"name": "The Peninsula Hong Kong", "city": "Hong Kong", "country": "China", "latitude": 22.2945, "longitude": 114.1720, "star_rating": 5.0, "description": "Legendary luxury hotel in Kowloon.", "address": "Salisbury Rd, Tsim Sha Tsui, Hong Kong", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool", "Helipad"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Harbour View", "price": 680, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.8, "text": "Absolute perfection!", "author": "Emily W."}]},
    {"name": "Yesinn Hostel Hong Kong", "city": "Hong Kong", "country": "China", "latitude": 22.2813, "longitude": 114.1589, "star_rating": 2.0, "description": "Budget hostel in Causeway Bay.", "address": "429 Lockhart Rd, Wan Chai, Hong Kong", "amenities": ["Wi-Fi", "Kitchen", "Lounge"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "4-Bed Dorm", "price": 35, "beds": "Bunk", "max_guests": 1}], "reviews": [{"rating": 7.6, "text": "Clean and basic.", "author": "Kevin L."}]},
    
    # Melbourne (3 hotels)
    {"name": "The Langham Melbourne", "city": "Melbourne", "country": "Australia", "latitude": -37.8197, "longitude": 144.9559, "star_rating": 5.0, "description": "Luxury hotel on Southbank.", "address": "1 Southgate Ave, Southbank, Melbourne VIC 3006", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa", "Pool"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "River View", "price": 420, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.4, "text": "Elegant and refined!", "author": "Sophie M."}]},
    {"name": "Base Backpackers Melbourne", "city": "Melbourne", "country": "Australia", "latitude": -37.8136, "longitude": 144.9631, "star_rating": 2.0, "description": "Party hostel in CBD.", "address": "17 Corrs Lane, Melbourne VIC 3000", "amenities": ["Wi-Fi", "Bar"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "8-Bed Dorm", "price": 30, "beds": "Bunk", "max_guests": 1}], "reviews": [{"rating": 7.5, "text": "Great for meeting people!", "author": "Jake R."}]},
    
    # Prague (4 hotels)
    {"name": "Four Seasons Hotel Prague", "city": "Prague", "country": "Czech Republic", "latitude": 50.0866, "longitude": 14.4124, "star_rating": 5.0, "description": "Luxury hotel on the Vltava River.", "address": "Veleslavínova 1098/2a, Prague 110 00", "amenities": ["Wi-Fi", "Restaurant", "Bar", "Spa"], "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200"], "rooms": [{"type": "Deluxe", "price": 380, "beds": "King", "max_guests": 2}], "reviews": [{"rating": 9.6, "text": "Fairytale setting!", "author": "Petra K."}]},
    {"name": "Czech Inn", "city": "Prague", "country": "Czech Republic", "latitude": 50.0875, "longitude": 14.4458, "star_rating": 3.0, "description": "Design hostel in Vinohrady.", "address": "Francouzská 76, Prague 101 00", "amenities": ["Wi-Fi", "Bar", "Garden"], "images": ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200"], "rooms": [{"type": "Private", "price": 60, "beds": "Double", "max_guests": 2}], "reviews": [{"rating": 8.5, "text": "Stylish and affordable!", "author": "Martin B."}]},
]

